services:
  nginx:
    labels:
      - "traefik.http.middlewares.${PROJECT_NAME}_nginx-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${PROJECT_NAME}_nginx.middlewares=${PROJECT_NAME}_nginx-redirect"
      - "traefik.http.routers.${PROJECT_NAME}_nginx-secure.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}_nginx-secure.rule=Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.${PROJECT_NAME}_nginx-secure.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}_nginx-secure.tls.domains.main=${PROJECT_BASE_URL}"
      - "traefik.http.routers.${PROJECT_NAME}_nginx-secure.tls.domains.san=${PROJECT_SAN_URL}"
      - "traefik.http.routers.${PROJECT_NAME}_nginx-secure.tls.certresolver=letsencrypt_${LETS_ENCRYPT_TARGET}"
      # - "traefik.http.routers.${PROJECT_NAME}_nginx-secure.service=${PROJECT_NAME}_nginx"

  traefik:
    command: --configFile=/etc/traefik/traefik.yml
    environment:
      TRAEFIK_CERTIFICATESRESOLVERS_letsencrypt_live_ACME_EMAIL: ${SYSADMIN_MAIL}
      TRAEFIK_CERTIFICATESRESOLVERS_letsencrypt_test_ACME_EMAIL: ${SYSADMIN_MAIL}
    ports:
      - '443:443'
    # labels:
      # - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=http"
      # - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      # - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_ACCESS_HASH}"
      # - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      # - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${PROJECT_BASE_URL}`)"
      # - "traefik.http.routers.traefik-secure.service=api@internal"
      # - "traefik.http.routers.traefik-secure.tls=true"
      # - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"