services:
  nginx:
    labels:
      - "traefik.http.middlewares.${PROJECT_NAME}_nginx-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${PROJECT_NAME}_nginx.middlewares=${PROJECT_NAME}_nginx-redirect"
      - "traefik.http.routers.${PROJECT_NAME}_nginx-secure.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}_nginx-secure.rule=HostRegexp(`${PROJECT_URL_PATTERN}`)"
      - "traefik.http.routers.${PROJECT_NAME}_nginx-secure.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}_nginx-secure.tls.domains[0].main=${PROJECT_BASE_URL}"
      - "traefik.http.routers.${PROJECT_NAME}_nginx-secure.tls.domains[0].sans=${PROJECT_SAN_URL}"
      - "traefik.http.routers.${PROJECT_NAME}_nginx-secure.tls.certresolver=letsencrypt_${LETS_ENCRYPT_TARGET}"
      - "traefik.http.routers.${PROJECT_NAME}_nginx-secure.service=${PROJECT_NAME}_nginx"

  traefik:
    environment:
      TRAEFIK_CERTIFICATESRESOLVERS_letsencrypt_live_ACME_EMAIL: ${SYSADMIN_MAIL}
      TRAEFIK_CERTIFICATESRESOLVERS_letsencrypt_test_ACME_EMAIL: ${SYSADMIN_MAIL}
    ports:
      - '443:443'
