map $http_user_agent $badagent {
  default   0;
  ~*gptbot  1;
  ~*chatgpt 1;
  ~*ccbot   1;
  ~*claude  1;
}

# geo $badrange {
#   default      0;
#   47.76.0.0/14 1;
#   47.80.0.0/13 1;
#   47.74.0.0/15 1;
# }
